import { HttpErrorResponse } from '@angular/common/http';
import { Injectable, inject } from '@angular/core';
import { BehaviorSubject, Observable, type Subscription } from 'rxjs';
import type {
  ApiResponse,
  SynthesizeSpeechRequest,
  TranscribeSpeechData,
} from '@voice-chat/shared';
import { ApiService } from './api.service';

const MAX_AUDIO_CACHE_ENTRIES = 20;

/** Mirrors the backend upload floor so an accidental click fails locally with a clear message. */
const MIN_RECORDING_BYTES = 1_024;

/** Mirrors the backend upload ceiling so an over-long clip fails before it is uploaded. */
const MAX_RECORDING_BYTES = 10 * 1024 * 1024;

/**
 * Recorder containers in descending preference. Chromium and Firefox produce WebM/Opus; Safari
 * falls back to MP4/AAC. The backend accepts every entry here.
 */
const RECORDER_MIME_CANDIDATES: readonly string[] = [
  'audio/webm;codecs=opus',
  'audio/webm',
  'audio/ogg;codecs=opus',
  'audio/mp4',
];

interface RecordingSession {
  recorder: MediaRecorder;
  stream: MediaStream;
  chunks: Blob[];
}

/** Controls an in-flight dictation session from outside its observable. */
interface ListeningHandle {
  /** Finishes recording and transcribes what was captured. */
  stop: () => void;
  /** Discards the recording and any in-flight upload without producing a transcript. */
  cancel: () => void;
}

/**
 * Browser adapter for dictation and playback, both transcribed and generated by the backend.
 *
 * Microphone audio is recorded locally with `MediaRecorder` and uploaded to the authenticated
 * backend, which forwards it to ElevenLabs. The provider credential never reaches the browser.
 */
@Injectable({ providedIn: 'root' })
export class SpeechService {
  readonly recordingSupported =
    typeof navigator !== 'undefined' &&
    typeof navigator.mediaDevices?.getUserMedia === 'function' &&
    typeof MediaRecorder !== 'undefined';
  readonly synthesisSupported =
    typeof window !== 'undefined' &&
    typeof Audio !== 'undefined' &&
    typeof URL !== 'undefined' &&
    typeof URL.createObjectURL === 'function';

  private readonly api = inject(ApiService);
  private readonly listeningSubject = new BehaviorSubject(false);
  private readonly transcribingSubject = new BehaviorSubject(false);
  private readonly speakingSubject = new BehaviorSubject(false);
  private readonly errorSubject = new BehaviorSubject<string | null>(null);
  readonly listening$ = this.listeningSubject.asObservable();
  readonly transcribing$ = this.transcribingSubject.asObservable();
  readonly speaking$ = this.speakingSubject.asObservable();
  readonly error$ = this.errorSubject.asObservable();

  private activeListening: ListeningHandle | null = null;
  private activeTranscriptionRequest: Subscription | null = null;
  private activeSpeechRequest: Subscription | null = null;
  private activeAudio: HTMLAudioElement | null = null;
  private activeAudioUrl: string | null = null;
  private speechGeneration = 0;
  private readonly audioCache = new Map<string, Blob>();

  /**
   * Records one dictation clip and emits the transcript the backend returns.
   *
   * The observable emits at most once, after {@link stopListening} finishes the recording and the
   * upload resolves. Unsubscribing discards the audio without transcribing it.
   */
  startListening(): Observable<string> {
    return new Observable<string>((subscriber) => {
      if (!this.recordingSupported) {
        const message = 'Microphone recording is not supported in this browser.';
        this.errorSubject.next(message);
        subscriber.error(new Error(message));
        return undefined;
      }

      this.abortListening();
      this.stopSpeaking();
      this.errorSubject.next(null);

      let session: RecordingSession | null = null;
      let settled = false;
      let stopRequested = false;

      const releaseHandle = (): void => {
        if (this.activeListening === handle) this.activeListening = null;
      };
      const discardRecording = (): void => {
        this.teardownSession(session);
        session = null;
        this.listeningSubject.next(false);
      };
      const cancelUpload = (): void => {
        this.activeTranscriptionRequest?.unsubscribe();
        this.activeTranscriptionRequest = null;
        this.transcribingSubject.next(false);
      };
      const fail = (message: string): void => {
        if (settled) return;
        settled = true;
        cancelUpload();
        discardRecording();
        releaseHandle();
        this.errorSubject.next(message);
        subscriber.error(new Error(message));
      };
      const succeed = (transcript: string): void => {
        if (settled) return;
        settled = true;
        this.transcribingSubject.next(false);
        releaseHandle();
        subscriber.next(transcript);
        subscriber.complete();
      };
      const cancel = (): void => {
        if (settled) return;
        settled = true;
        cancelUpload();
        discardRecording();
        releaseHandle();
        subscriber.complete();
      };
      const stop = (): void => {
        if (settled || stopRequested) return;
        stopRequested = true;
        // Permission is still pending, so nothing has been captured yet.
        if (!session) {
          cancel();
          return;
        }
        this.listeningSubject.next(false);
        this.transcribingSubject.next(true);
        try {
          if (session.recorder.state !== 'inactive') session.recorder.stop();
        } catch {
          fail('The recording could not be finished. Please try again.');
        }
      };

      const handle: ListeningHandle = { stop, cancel };
      this.activeListening = handle;

      void navigator.mediaDevices
        .getUserMedia({ audio: true })
        .then((stream) => {
          if (settled) {
            for (const track of stream.getTracks()) track.stop();
            return;
          }

          let recorder: MediaRecorder;
          try {
            recorder = this.createRecorder(stream);
          } catch {
            for (const track of stream.getTracks()) track.stop();
            fail('The microphone recorder could not be started in this browser.');
            return;
          }

          const active: RecordingSession = { recorder, stream, chunks: [] };
          recorder.ondataavailable = (event) => {
            if (event.data.size) active.chunks.push(event.data);
          };
          recorder.onerror = () => fail('The microphone recording failed. Please try again.');
          recorder.onstop = () => {
            const type = recorder.mimeType || active.chunks[0]?.type || 'audio/webm';
            const recording = new Blob(active.chunks, { type });
            discardRecording();
            if (settled) return;
            this.transcribeRecording(recording, succeed, fail);
          };

          session = active;
          try {
            recorder.start();
          } catch {
            fail('The microphone could not be started. Check browser permissions and try again.');
            return;
          }
          this.listeningSubject.next(true);

          // A stop arriving while permission was pending applies as soon as recording begins.
          if (stopRequested) {
            stopRequested = false;
            stop();
          }
        })
        .catch((error: unknown) => fail(this.microphoneErrorMessage(error)));

      return () => cancel();
    });
  }

  /** Finishes the active recording so it can be transcribed. */
  stopListening(): void {
    this.activeListening?.stop();
  }

  /** Discards the active recording and any pending transcription without producing a transcript. */
  abortListening(): void {
    this.activeListening?.cancel();
  }

  /** Requests natural English audio from the authenticated backend and plays it locally. */
  speak(text: string): void {
    const content = text.trim();
    if (!content) return;
    if (!this.synthesisSupported) {
      this.errorSubject.next('Audio playback is not supported in this browser.');
      return;
    }

    // Playback through the speakers would otherwise be captured by an open microphone.
    this.abortListening();
    this.stopSpeaking();
    this.errorSubject.next(null);
    const generation = this.speechGeneration;
    const cachedAudio = this.audioCache.get(content);
    if (cachedAudio) {
      this.playAudioBlob(cachedAudio, generation);
      return;
    }

    this.speakingSubject.next(true);
    const request: SynthesizeSpeechRequest = { text: content };
    const subscription = this.api.postBlob('/speech/synthesize', request).subscribe({
      next: (audioBlob) => {
        if (generation !== this.speechGeneration) return;
        this.activeSpeechRequest = null;
        if (!audioBlob.size || !audioBlob.type.toLowerCase().startsWith('audio/')) {
          this.failSpeech(generation, 'The voice service returned invalid audio.');
          return;
        }
        this.cacheAudio(content, audioBlob);
        this.playAudioBlob(audioBlob, generation);
      },
      error: (error: unknown) => {
        this.failSpeech(generation, this.synthesisErrorMessage(error));
      },
    });
    this.activeSpeechRequest = subscription.closed ? null : subscription;
  }

  /** Cancels the active cloud request or audio playback and releases browser resources. */
  stopSpeaking(): void {
    this.speechGeneration += 1;
    this.activeSpeechRequest?.unsubscribe();
    this.activeSpeechRequest = null;

    const audio = this.activeAudio;
    this.activeAudio = null;
    if (audio) {
      audio.onplay = null;
      audio.onended = null;
      audio.onerror = null;
      audio.pause();
      audio.removeAttribute('src');
      audio.load();
    }
    this.releaseAudioUrl();
    this.speakingSubject.next(false);
  }

  private createRecorder(stream: MediaStream): MediaRecorder {
    for (const mimeType of RECORDER_MIME_CANDIDATES) {
      if (
        typeof MediaRecorder.isTypeSupported === 'function' &&
        MediaRecorder.isTypeSupported(mimeType)
      )
        return new MediaRecorder(stream, { mimeType });
    }
    return new MediaRecorder(stream);
  }

  /** Detaches recorder handlers and releases the microphone so the browser drops its indicator. */
  private teardownSession(session: RecordingSession | null): void {
    if (!session) return;
    session.recorder.ondataavailable = null;
    session.recorder.onerror = null;
    session.recorder.onstop = null;
    try {
      if (session.recorder.state !== 'inactive') session.recorder.stop();
    } catch {
      // The recorder was already torn down by the browser; releasing the tracks is what matters.
    }
    for (const track of session.stream.getTracks()) track.stop();
  }

  private transcribeRecording(
    recording: Blob,
    succeed: (transcript: string) => void,
    fail: (message: string) => void,
  ): void {
    if (recording.size < MIN_RECORDING_BYTES) {
      fail('No speech was detected. Check your microphone and try again.');
      return;
    }
    if (recording.size > MAX_RECORDING_BYTES) {
      fail('The recording is too long. Record a shorter message and try again.');
      return;
    }

    this.transcribingSubject.next(true);
    const contentType = recording.type || 'audio/webm';
    const subscription = this.api
      .postBinary<ApiResponse<TranscribeSpeechData>>('/speech/transcribe', recording, contentType)
      .subscribe({
        next: (response) => {
          this.activeTranscriptionRequest = null;
          const transcript = response.data.text.trim();
          if (!transcript) {
            fail('No speech was detected. Check your microphone and try again.');
            return;
          }
          succeed(transcript);
        },
        error: (error: unknown) => {
          this.activeTranscriptionRequest = null;
          fail(this.transcriptionErrorMessage(error));
        },
      });
    this.activeTranscriptionRequest = subscription.closed ? null : subscription;
  }

  private microphoneErrorMessage(error: unknown): string {
    switch (error instanceof Error ? error.name : '') {
      case 'NotAllowedError':
      case 'SecurityError':
        return 'Microphone permission was denied. Allow microphone access in browser settings.';
      case 'NotFoundError':
      case 'OverconstrainedError':
        return 'No working microphone was found. Check your audio input device.';
      case 'NotReadableError':
        return 'The microphone is in use by another application. Close it and try again.';
      default:
        return 'The microphone could not be started. Check browser permissions and try again.';
    }
  }

  private transcriptionErrorMessage(error: unknown): string {
    const fallback = 'The recording could not be transcribed. Please try again.';
    if (!(error instanceof HttpErrorResponse)) return fallback;
    if (error.status === 0)
      return 'The transcription request could not reach the server. Check your connection.';

    switch (this.errorCode(error)) {
      case 'SPEECH_NOT_CONFIGURED':
        return 'Transcription is not configured. Set ELEVENLABS_API_KEY in the backend environment.';
      case 'SPEECH_NO_SPEECH_DETECTED':
        return 'No speech was detected. Check your microphone and try again.';
      case 'SPEECH_UPLOAD_TOO_LARGE':
        return 'The recording is too long. Record a shorter message and try again.';
      case 'SPEECH_RATE_LIMITED':
        return 'Too many voice requests. Wait a minute and try again.';
      default:
        return error.status === 401
          ? 'Your session expired. Sign in again to use dictation.'
          : fallback;
    }
  }

  private synthesisErrorMessage(error: unknown): string {
    const fallback = 'Natural English voice could not be generated. Please try again.';
    if (!(error instanceof HttpErrorResponse)) return fallback;

    switch (this.errorCode(error)) {
      case 'SPEECH_NOT_CONFIGURED':
        return 'Playback is not configured. Set ELEVENLABS_API_KEY in the backend environment.';
      case 'SPEECH_RATE_LIMITED':
        return 'Too many voice requests. Wait a minute and try again.';
      default:
        return fallback;
    }
  }

  /**
   * Reads the API error code from a failed request.
   *
   * Blob-typed responses arrive unparsed, so only JSON envelopes expose a code; callers fall back
   * to a generic message when this returns an empty string.
   */
  private errorCode(error: HttpErrorResponse): string {
    const body = error.error as unknown;
    if (typeof body !== 'object' || body === null) return '';
    const envelope = (body as { error?: { code?: unknown } }).error;
    return typeof envelope?.code === 'string' ? envelope.code : '';
  }

  private playAudioBlob(audioBlob: Blob, generation: number): void {
    if (generation !== this.speechGeneration) return;
    const audioUrl = URL.createObjectURL(audioBlob);
    const audio = new Audio(audioUrl);
    audio.preload = 'auto';
    audio.onplay = () => {
      if (this.activeAudio === audio && generation === this.speechGeneration)
        this.speakingSubject.next(true);
    };
    audio.onended = () => this.finishAudio(audio, audioUrl);
    audio.onerror = () => {
      if (this.activeAudio !== audio) return;
      this.finishAudio(audio, audioUrl);
      this.errorSubject.next('The browser could not play the generated English audio.');
    };

    this.activeAudio = audio;
    this.activeAudioUrl = audioUrl;
    this.speakingSubject.next(true);
    void audio.play().catch(() => {
      if (this.activeAudio !== audio || generation !== this.speechGeneration) return;
      this.finishAudio(audio, audioUrl);
      this.errorSubject.next(
        'The browser blocked audio playback. Select Listen again to allow sound.',
      );
    });
  }

  private finishAudio(audio: HTMLAudioElement, audioUrl: string): void {
    if (this.activeAudio !== audio) return;
    audio.onplay = null;
    audio.onended = null;
    audio.onerror = null;
    audio.removeAttribute('src');
    audio.load();
    this.activeAudio = null;
    if (this.activeAudioUrl === audioUrl) {
      URL.revokeObjectURL(audioUrl);
      this.activeAudioUrl = null;
    }
    this.speakingSubject.next(false);
  }

  private failSpeech(generation: number, message: string): void {
    if (generation !== this.speechGeneration) return;
    this.activeSpeechRequest = null;
    this.speakingSubject.next(false);
    this.errorSubject.next(message);
  }

  private cacheAudio(text: string, audioBlob: Blob): void {
    this.audioCache.delete(text);
    while (this.audioCache.size >= MAX_AUDIO_CACHE_ENTRIES) {
      const oldestKey = this.audioCache.keys().next().value as string | undefined;
      if (!oldestKey) break;
      this.audioCache.delete(oldestKey);
    }
    this.audioCache.set(text, audioBlob);
  }

  private releaseAudioUrl(): void {
    if (!this.activeAudioUrl) return;
    URL.revokeObjectURL(this.activeAudioUrl);
    this.activeAudioUrl = null;
  }
}
